# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e0c63b33ec4a71e0289ccdb5b7528e48be52194e753b3dea4b1d23c3f9fb8dd882603a49cb868d904bffb0314510ee5d9018760da9d070e76aa0c5fa7c7d8d2

test:
  secret_key_base: 47e48912be8bc959d30f9592595c753d04f30507066950bb6ac4f74b70a8f1c73f604dc9d77889d3d4494953c19b415574a129ea4fd7b02b8044799bf4306832

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
